
cache:
  directories:
  - $HOME/.portage

matrix:
  include:
    - os: linux
      services: docker
      language: generic
      sudo: required
      script:
        - bash ./travis/emerge-new-ebuilds.sh
    - os: linux
      services: docker
      language: generic
      sudo: required
      script:
        - bash ./travis/emerge-new-ebuilds.sh


      
